.PHONY: clean All

All:
	@echo "----------Building project:[ Project3 - Debug ]----------"
	@cd "Project3" && "$(MAKE)" -f  "Project3.mk"
clean:
	@echo "----------Cleaning project:[ Project3 - Debug ]----------"
	@cd "Project3" && "$(MAKE)" -f  "Project3.mk" clean
