.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge16(ReadFile) - Debug ]----------"
	@cd "Challenge16(ReadFile)" && "$(MAKE)" -f  "Challenge16(ReadFile).mk"
clean:
	@echo "----------Cleaning project:[ Challenge16(ReadFile) - Debug ]----------"
	@cd "Challenge16(ReadFile)" && "$(MAKE)" -f  "Challenge16(ReadFile).mk" clean
