.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge17(ReadFile) - Debug ]----------"
	@cd "Challenge17(ReadFile)" && "$(MAKE)" -f  "Challenge17(ReadFile).mk"
clean:
	@echo "----------Cleaning project:[ Challenge17(ReadFile) - Debug ]----------"
	@cd "Challenge17(ReadFile)" && "$(MAKE)" -f  "Challenge17(ReadFile).mk" clean
