.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge18(ReWriteFile) - Debug ]----------"
	@cd "Challenge18(ReWriteFile)" && "$(MAKE)" -f  "Challenge18(ReWriteFile).mk"
clean:
	@echo "----------Cleaning project:[ Challenge18(ReWriteFile) - Debug ]----------"
	@cd "Challenge18(ReWriteFile)" && "$(MAKE)" -f  "Challenge18(ReWriteFile).mk" clean
