.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge_22(Stack_Queue) - Debug ]----------"
	@cd "Challenge_22(Stack_Queue)" && "$(MAKE)" -f  "Challenge_22(Stack_Queue).mk"
clean:
	@echo "----------Cleaning project:[ Challenge_22(Stack_Queue) - Debug ]----------"
	@cd "Challenge_22(Stack_Queue)" && "$(MAKE)" -f  "Challenge_22(Stack_Queue).mk" clean
