.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge_20(List) - Debug ]----------"
	@cd "Challenge_20(List)" && "$(MAKE)" -f  "Challenge_20(List).mk"
clean:
	@echo "----------Cleaning project:[ Challenge_20(List) - Debug ]----------"
	@cd "Challenge_20(List)" && "$(MAKE)" -f  "Challenge_20(List).mk" clean
