.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge_21(Using_Set_and_Map) - Debug ]----------"
	@cd "Challenge_21(Using_Set_and_Map)" && "$(MAKE)" -f  "Challenge_21(Using_Set_and_Map).mk"
clean:
	@echo "----------Cleaning project:[ Challenge_21(Using_Set_and_Map) - Debug ]----------"
	@cd "Challenge_21(Using_Set_and_Map)" && "$(MAKE)" -f  "Challenge_21(Using_Set_and_Map).mk" clean
