.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge7 - Debug ]----------"
	@cd "Challenge7" && "$(MAKE)" -f  "Challenge7.mk"
clean:
	@echo "----------Cleaning project:[ Challenge7 - Debug ]----------"
	@cd "Challenge7" && "$(MAKE)" -f  "Challenge7.mk" clean
