.PHONY: clean All

All:
	@echo "----------Building project:[ StatefulLambda - Debug ]----------"
	@cd "StatefulLambda" && "$(MAKE)" -f  "StatefulLambda.mk"
clean:
	@echo "----------Cleaning project:[ StatefulLambda - Debug ]----------"
	@cd "StatefulLambda" && "$(MAKE)" -f  "StatefulLambda.mk" clean
