.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge9 - Debug ]----------"
	@cd "Challenge9" && "$(MAKE)" -f  "Challenge9.mk"
clean:
	@echo "----------Cleaning project:[ Challenge9 - Debug ]----------"
	@cd "Challenge9" && "$(MAKE)" -f  "Challenge9.mk" clean
