.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge12(Polymorphism) - Debug ]----------"
	@cd "Challenge12(Polymorphism)" && "$(MAKE)" -f  "Challenge12(Polymorphism).mk"
clean:
	@echo "----------Cleaning project:[ Challenge12(Polymorphism) - Debug ]----------"
	@cd "Challenge12(Polymorphism)" && "$(MAKE)" -f  "Challenge12(Polymorphism).mk" clean
