.PHONY: clean All

All:
	@echo "----------Building project:[ Mystring-start_practice - Debug ]----------"
	@cd "Mystring-start_practice" && "$(MAKE)" -f  "Mystring-start_practice.mk"
clean:
	@echo "----------Cleaning project:[ Mystring-start_practice - Debug ]----------"
	@cd "Mystring-start_practice" && "$(MAKE)" -f  "Mystring-start_practice.mk" clean
